---

- hosts: all
  become: true
  pre_tasks:
    - name: Pre-run | update package cache (arch, manjaro)
      pacman:
        update_cache: yes
        upgrade: yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: Pre-run | update package cache (debian, etc)
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "*"
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Pre-run | update package cache (fedora)
      dnf:
        update_only: yes
        name: "*"
        state: latest
      changed_when: False
      when: ansible_distribution == "Fedora"

# run roles
- hosts: all
  become: true
  roles:
    - base

- hosts: workstation
  become: true
  become_user: "{{ custom_user }}"
  roles:
    - workstation

- hosts: server
  become: true
  roles:
    - server

# end of run cleanup and reporting
- hosts: all
  become: true
  tasks:
    - name: Cleanup packages (arch)
      shell: yes | pacman -Scc
      when: ansible_distribution == "Archlinux"

    - name: Cleanup package cache (debian and ubuntu)
      apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Autoremove orphan packages (debian and ubuntu)
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Cleanup package cache (fedora)
      dnf:
        autoremove: yes
      when: ansible_distribution == "Fedora"

    - name: Send completion alert
      include_tasks: playbooks/send_completion_alert.yml
      when:
        - task_failed is not defined

    - name: Send failure alert
      include_tasks: playbooks/send_failure_alert.yml
      when:
        - task_failed is defined
        - task_failed == true
