---
- name: Update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Restart sshd
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    state: restarted
  failed_when: true

- name: Source profile
  ansible.builtin.shell: "source /home/{{ custom_user }}/{{ item.file }}"
  with_items:
    - { file: ".bashrc" }
    - { file: ".zshrc" }
