---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: enable_ufw
  service:
    name: ufw
    state: started
    enabled: yes