---

- name: Users | custom user | create personal config directories
  file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { dir: github }
    - { dir: tmp }
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: .local/share/kservices5 }
    - { dir: .local/share/kwin/scripts }
    - { dir: .local/share/kwin/scripts/forceblur }
    - { dir: .icons }

- name: Users | custom user | copy user-dirs.dirs
  copy:
    src: users/custom_user/user-dirs.dirs
    dest: "/home/{{ custom_user }}/.config/user-dirs.dirs"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0600
  notify: update_xdg

- name: Users | custom user | copy personal config files
  copy:
    src: "users/custom_user/{{ item.src }}"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { src: 'bpytop.conf', dest: '.config/bpytop/bpytop.conf' }
    - { src: 'resources/splash_screen/ksplashrc', dest: '.config' }
    - { src: 'resources/walls', dest: '/.local/share/wallpapers/' }

#- name: Users | custom user | copy profile image
#  copy:
#    src: "users/custom_user/profile_image.png"
#    dest: "/var/lib/AccountsService/icons/{{ custom_user }}.png"
#    owner: root
#    group: root
#    mode: 0644
#  become_user: root
