---

- name: Users | custom user | stat .config folder
  stat:
    path: "/home/{{ custom_user }}/.config"
  register: config_dir

- name: Users | custom user | create config directories
  file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0700
  with_items:
    - { dir: '.config' }
  when: config_dir.stat.exists == false

- name: Users | custom user | create personal config directories
  file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: .local/share/kservices5 }
    - { dir: .local/share/kwin/scripts }
    - { dir: .local/share/kwin/scripts/forceblur }
    - { dir: .icons }

- name: Users | custom user | clone backups
  become_user: "{{ custom_user }}"
  git:
    repo: https://github.com/jokerwrld999/ultimate-backup.git
    dest: "{{ tmp_dir }}/ultimate-backup"
    force: yes

- name: Users | custom user | restore backup files
  copy:
    src: "{{ tmp_dir }}/ultimate-backup/{{ item.src }}"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { src: 'fonts', dest: '.local/share/' }
    - { src: 'walls', dest: '/.local/share/wallpapers/' }

- name: Users | custom user | copy personal config files
  copy:
    src: "users/custom_user/{{ item.src }}"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { src: 'bpytop.conf', dest: '.config/bpytop/bpytop.conf' }
    - { src: 'resources/splash_screen/ksplashrc', dest: '.config' }
