---

- block:
  ## User configs
  - import_tasks: users/custom_user.yml

## desktop environments

  - include_tasks: desktop_environments/kde/kde.yml
  - include_tasks: desktop_environments/kde/plasmoids.yml
  - include_tasks: desktop_environments/kde/theme.yml

  ## System setup
  - import_tasks: system_setup/scripts.yml

  ## install software
  - import_tasks: software/flameshot.yml
  - import_tasks: software/foliate.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/latte_dock.yml  
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/telegram.yml
  - import_tasks: software/terraform.yml
  - import_tasks: software/virtual_desktop_bar.yml
  - import_tasks: software/vlc.yml
  - import_tasks: software/vpn.yml
  - import_tasks: software/vs_code.yml

  rescue:
    - set_fact: task_failed=true
    