---
- name: Desktop Configuration
  block:
    # User configs
    - name: Desktop Configuration | Configure User
      ansible.builtin.import_tasks: user_setup/user_config.yml

    # Desktop environments
    - name: Desktop Configuration | Configure KDE
      ansible.builtin.import_tasks: desktop_environments/kde/kde.yml
    - name: Desktop Configuration | Configure Plasmoids
      ansible.builtin.import_tasks: desktop_environments/kde/plasmoids.yml
    - name: Desktop Configuration | Configure Customization
      ansible.builtin.import_tasks: desktop_environments/kde/customization.yml

    # Install software
    - name: Desktop Configuration | Install
      ansible.builtin.import_tasks: software/chrome.yml
    - name: Desktop Configuration | Install Flameshot
      ansible.builtin.import_tasks: software/flameshot.yml
    - name: Desktop Configuration | Install Latte Dock
      ansible.builtin.import_tasks: software/latte_dock.yml
    - name: Desktop Configuration | Install LibreOffice
      ansible.builtin.import_tasks: software/libreoffice.yml
    - name: Desktop Configuration | Install Telegram
      ansible.builtin.import_tasks: software/telegram.yml
    - name: Desktop Configuration | Install VLC
      ansible.builtin.import_tasks: software/vlc.yml
    - name: Desktop Configuration | Install VPN
      ansible.builtin.import_tasks: software/vpn.yml
    - name: Desktop Configuration | Install VSCode
      ansible.builtin.import_tasks: software/vs_code.yml

  rescue:
    - name: Desktop Configuration | Rescue
      ansible.builtin.set_fact:
        task_failed: true
