---
- name: Software | Development | Install packages
  ansible.builtin.package:
    name:
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_psutil_package }}"
      - "{{ python_virtualenv_package }}"
      - pipx
    state: latest

- name: Software | Development | Install packages Arch
  community.general.pacman:
    name:
      - base-devel
  when: ansible_distribution == "Archlinux"

- name: Software | Development | Install packages Debian
  ansible.builtin.apt:
    name:
      - build-essential
      - python-is-python3
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Development | Install packages Fedora
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - "@Development libraries"
    state: latest
  when: ansible_distribution == "Fedora"

- name: Software | Development | Install python packages
  community.general.pipx:
    name: "{{ item.package }}"
    install_deps: true
    state: latest
  with_items:
    - { package: "boto3" }
    - { package: "docker" }
    - { package: "botocore" }
    - { package: "requests" }
