---
- name: Software | Development | Install packages
  ansible.builtin.package:
    name:
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_virtualenv_package }}"
    state: latest

- name: Software | Development | Install packages Arch
  community.general.pacman:
    name:
      - base-devel
  when: ansible_distribution == "Archlinux"

- name: Software | Development | Install packages Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - build-essential
      - python-is-python3
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Development | Install packages Fedora
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - "@Development libraries"
    state: latest
  when: ansible_distribution == "Fedora"

- name: Software | Development | Check for python packages
  ansible.builtin.command: pip3 show boto3
  register: check_pip
  ignore_errors: true

- name: Software | Development | Install python packages
  ansible.builtin.shell: |
    pip install "{{ item.package }}" --break-system-packages
  with_items:
    - { package: "boto3" }
    - { package: "botocore" }
    - { package: "bpytop" }
    - { package: "docker" }
    - { package: "requests" }
  when: check_pip.stdout.find('WARNING') != -1
