---
- name: Software | Docker | Install package Arch
  community.general.pacman:
    name: docker
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Software | Docker | Install package Debian/Ubuntu
  ansible.builtin.shell: |
    curl https://get.docker.com | bash
  args:
    creates: /usr/bin/docker
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Docker | Install package Fedora
  ansible.builtin.dnf:
    name: docker
    state: latest
  when: ansible_distribution == "Fedora"

- name: Software | Docker | Create group
  ansible.builtin.group:
    name: docker
    state: present

- name: Software | Docker | Add user to group
  ansible.builtin.user:
    name: "{{ custom_user }}"
    groups: docker
    append: yes

- name: Software | Docker | Reconnect to server session
  ansible.builtin.meta: reset_connection

- name: Software | Docker Compose | Install package
  ansible.builtin.package:
    name:
      - docker-compose

- name: Software | Docker | Change permissions
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: "0666"

- name: Software | Docker | Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
