# source bash prompt
source ~/.bash/bash_prompt

# Source bash aliases
source ~/.bash/bash_aliases

# Source bash functions
source ~/.bash/bash_functions

# Env
export TERM=xterm-256color
export EDITOR=nano

# Show system information at login
if [ -t 0 ]; then
    if type -p "neofetch" > /dev/null; then
        neofetch
    else
        echo "Warning: neofetch was called, but it's not installed."
    fi
fi

# Don't add duplicate lines or lines beginning with a space to the history
HISTCONTROL=ignoreboth

# Set history format to include timestamps
HISTTIMEFORMAT="%Y-%m-%d %T "

# Add /home/$USER/bin to $PATH
case :$PATH: in
	*:/home/$USER/bin:*) ;;
	*) PATH=/home/$USER/bin:$PATH ;;
esac

# Add /home/$USER/.local/bin to $PATH
case :$PATH: in
	*:/home/$USER/.local/bin:*) ;;
	*) PATH=/home/$USER/.local/bin:$PATH ;;
esac

# reload bash config
alias reload="source ~/.bashrc"

export PATH="$HOME/.local/bin:$PATH"
