---

- name: Users | custom user | install base pkgs
  package:
    name:
      - zsh
      - git

- name: Users | custom user | create group
  group:
    name: "{{ custom_user }}"
    state: present

- name: Users | custom user | create user
  user:
    name: "{{ custom_user }}"
    group: "{{ custom_user }}"
    groups: "{{ custom_user }},{{ sudo_group }}"
    password: "{{ custom_user_passwd }}"
    update_password: on_create
    shell: /bin/zsh
    state: present

- name: Users | custom user | stat sudoers file
  stat:
    path: "/etc/sudoers.d/sudoers_{{ custom_user }}"
  register: sudoers_file

- name: Users | custom user | add sudoers file
  copy:
    src: "users/sudoers_custom_user"
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    owner: root
    group: root
    mode: 0440
  register: new_sudoers_file
  when: sudoers_file.stat.exists == false
  
- name: Users | custom user | change sudoers file
  lineinfile:
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    regexp: "^custom_user"
    line: "{{ custom_user }} ALL=(ALL) NOPASSWD: ALL"
  when: new_sudoers_file.changed

  
