---

- name: Users | custom user | create group
  group:
    name: "{{ custom_user }}"
    state: present
  register: custom_user_group

- name: Users | custom user | create user
  user:
    name: "{{ custom_user }}"
    group: "{{ custom_user }}"
    groups: "{{ custom_user }},{{ sudo_group }}"
    state: present
    password: "{{ custom_user_passwd }}"
    update_password: on_create
    shell: /bin/zsh
  when: custom_user_group.changed

- name: Users | custom user | stat sudoers file
  stat:
    path: "/etc/sudoers.d/sudoers_{{ custom_user }}"
  register: sudoers_file

- name: Users | custom user | add sudoers file
  copy:
    src: "users/sudoers_custom_user"
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    owner: root
    group: root
    mode: 0440
  register: new_sudoers_file
  when: sudoers_file.stat.exists == false
  
- name: Users | custom user | change sudoers file
  lineinfile:
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    regexp: "^custom_user"
    line: "{{ custom_user }} ALL=(ALL) NOPASSWD: ALL"
  when: new_sudoers_file.changed

- name: Users | custom user | stat authorized_keys file
  stat:
    path: "/home/{{ custom_user }}/.ssh/authorized_keys"
  register: authorized_keys

- name: Users | custom user | add public key
  become_user: "{{ custom_user }}"
  shell: "wget -O - https://github.com/jokerwrld999.keys | tee -a /home/{{ custom_user }}/.ssh/authorized_keys"
  args:
    executable: /bin/bash
  when: authorized_keys.stat.exists == false