---
# **** Installing Chrome | Debian-based
- name: Software | Chrome | Add repository key Debian
  become_user: root
  ansible.builtin.apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Chrome | Stat Chrome repo Debian
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/google-chrome.list"
  register: chrome_repo
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Chrome | Add repository Debian
  become_user: root
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu"] and chrome_repo.stat.exists == false

- name: Software | Chrome | Install package Debian
  become_user: root
  ansible.builtin.apt:
    name: google-chrome-stable
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

# **** Installing Chrome | Fedora
- name: Software | Chrome | Add repository Fedora
  become_user: root
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  when: ansible_distribution == "Fedora"

- name: Software | Chrome | Add repository Fedora
  become_user: root
  ansible.builtin.yum_repository:
    name: google-chrome
    description: google-chrome repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
  when: ansible_distribution == "Fedora"

- name: Software | Chrome | Install package Fedora
  become_user: root
  ansible.builtin.dnf:
    name: google-chrome-stable
    state: latest
  when: ansible_distribution == "Fedora"

# **** Installing Chrome | Arch-based
- name: Software | Chrome | Install package Archlinux
  kewlfft.aur.aur:
    use: yay
    name: google-chrome
  when: ansible_distribution == "Archlinux"
