---

# **** Installing Latte Dock Package | Fedora and Debian-based
- name: Software | latte_dock | install package
  become_user: root
  package:
    name: latte-dock
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Fedora"]

# **** Installing Latte Dock Package | Arch-based
- name: Software | latte_dock | install package
  kewlfft.aur.aur:
    use: yay
    name: latte-dock
  when: ansible_distribution == "Archlinux"
