---
# **** Installing Latte Dock Package | Fedora and Debian-based
- name: Software | Latte | Install package
  become_user: root
  ansible.builtin.package:
    name: latte-dock
  when: ansible_distribution in ["Debian", "Ubuntu", "Fedora", "Rocky"]

# **** Installing Latte Dock Package | Arch-based
- name: Software | Latte | Install package Arch
  kewlfft.aur.aur:
    use: yay
    name: latte-dock
  when: ansible_distribution == "Archlinux"
