---

# **** Installing VPN Packages | Debian-based
- name: Software | VPN | Install package Debian
  become_user: root
  apt:
    name:
      - strongswan
      - network-manager-strongswan
      - libcharon-extra-plugins
  when: ansible_distribution in ["Debian", "Ubuntu"]

# **** Installing VPN Packages | Fedora
- name: Software | VPN | Install package Fedora
  become_user: root
  dnf:
    name:
      - strongswan
      - NetworkManager-strongswan
  when: ansible_distribution == "Fedora"

# **** Installing VPN Packages | Arch-based
- name: Software | VPN | Install package Arch
  become_user: root
  pacman:
    name:
      - strongswan
      - networkmanager-strongswan
  when: ansible_distribution == "Archlinux"
