---

# **** Installing VS Code | Debian-based
- name: Software | Code | Add repository key Debian
  become_user: root
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Code | Add repository Debian
  become_user: root
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Code | Install package Debian
  become_user: root
  apt:
    name: code
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

# **** Installing VS Code | Fedora
- name: Software | Code | Add repository and key Fedora
  become_user: root
  ansible.builtin.yum_repository:
    name: vs_code
    description: Vs Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_distribution == "Fedora"

- name: Software | Code | Install package Fedora
  become_user: root
  dnf:
    name: code
  when: ansible_distribution == "Fedora"

# **** Installing VS Code | Arch-based
- name: Software | Code | Install package Arch
  kewlfft.aur.aur:
    use: yay
    name: visual-studio-code-bin
  when: ansible_distribution == "Archlinux"
