---
# **** Installing Theme Packages | Debian-based
- name: Customization | Install packages
  become_user: root
  ansible.builtin.apt:
    name:
      - gtk2-engines-murrine
      - sassc
      - qt5-style-kvantum
      - qt5-style-kvantum-themes
  when: ansible_distribution in ["Debian", "Ubuntu"]

# **** Installing Theme Packages | Fedora
- name: Customization | Install packages
  become_user: root
  ansible.builtin.dnf:
    name:
      - gtk-murrine-engine
      - sassc
      - kvantum
  when: ansible_distribution == "Fedora"

# **** Installing Theme Packages | Arch-based
- name: Customization | Install packages
  become_user: root
  community.general.pacman:
    name:
      - gtk-engine-murrine
      - sassc
      - kvantum-qt5
  when: ansible_distribution == "Archlinux"

  # **** Orchis KDE Theme
- name: Customization | Clone orchis-kde
  ansible.builtin.git:
    repo: https://github.com/vinceliuice/Orchis-kde.git
    dest: "~/{{ temp_dir }}/Orchis-kde"
    force: yes

- name: Customization | Install orchis-kde
  ansible.builtin.shell: |
    ./install.sh
  args:
    chdir: "~/{{ temp_dir }}/Orchis-kde/"
    creates: "/home/{{ custom_user }}/.local/share/plasma/desktoptheme/Orchis-dark"
  register: orchis_theme_installed

- name: Customization | apply desktop theme
  ansible.builtin.command: plasma-apply-desktoptheme Orchis-dark -platform offscreen
  when: orchis_theme_installed.changed

# **** Sevi Icon Theme
- name: Customization | Clone sevi icons
  ansible.builtin.git:
    repo: https://github.com/TaylanTatli/Sevi.git
    dest: "~/{{ temp_dir }}/Sevi"
    force: yes

- name: Customization | Install sevi icons
  ansible.builtin.shell: |
    ./install.sh -black
  args:
    chdir: "~/{{ temp_dir }}/Sevi/"
    creates: "/home/{{ custom_user }}/.local/share/icons/Sevi-black"
  register: sevi_icons_installed

- name: Customization | Apply icons
  ansible.builtin.shell: |
    changeicons=$(find /usr/ -name 'plasma-changeicons')
    $changeicons Sevi-black -platform offscreen
  when: sevi_icons_installed.changed

  # **** Bibata Cursors
- name: Customization | Install bibata cursors for user
  ansible.builtin.unarchive:
    src: users/custom_user/resources/cursors/Bibata-Modern-Ice.tar.gz
    dest: "{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { dest: "/home/{{ custom_user }}/.icons/" }
  register: bibata_cursors_installed

- name: Customization | Install bibata cursors for root
  become_user: root
  ansible.builtin.unarchive:
    src: users/custom_user/resources/cursors/Bibata-Modern-Ice.tar.gz
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - { dest: "/usr/share/icons/" }

- name: Customization | Apply cursor theme
  ansible.builtin.command: plasma-apply-cursortheme Bibata-Modern-Ice -platform offscreen
  when: bibata_cursors_installed.changed

# **** Force Blur
- name: Customization | Clone force blur
  ansible.builtin.git:
    repo: https://github.com/esjeon/kwin-forceblur.git
    dest: "~/{{ temp_dir }}/kwin-forceblur"
    force: yes

- name: Customization | Copy forceblur files
  ansible.builtin.copy:
    src: "~/{{ temp_dir }}/kwin-forceblur/metadata.desktop"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
    remote_src: true
  with_items:
    - { dest: ".local/share/kwin/scripts/forceblur/" }
    - { dest: ".local/share/kservices5/forceblur.desktop" }

# **** SDDM
- name: Customization | Clone swish sddm
  become_user: root
  ansible.builtin.git:
    repo: https://github.com/icaho/Swish.git
    dest: "~/{{ temp_dir }}/Swish"
    force: yes

- name: Customization | Create sddm directory
  become_user: root
  ansible.builtin.file:
    path: /etc/sddm.conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Customization | Stat sddm theme folder
  ansible.builtin.stat:
    path: "/usr/share/sddm/themes/Swish"
  register: sddm_theme

- name: Customization | Restore swish sddm
  become_user: root
  ansible.builtin.copy:
    src: "~/{{ temp_dir }}/Swish"
    dest: /usr/share/sddm/themes/
    owner: root
    group: root
    mode: 0755
  when: sddm_theme.stat.exists == false

- name: Customization | Restore a kde_settings
  become_user: root
  ansible.builtin.copy:
    src: users/custom_user/resources/sddm/kde_settings.conf
    dest: /etc/sddm.conf.d/
    owner: root
    group: root
    mode: 0755

- name: Customization | Restore plasma backup
  ansible.builtin.copy:
    src: "~/{{ temp_dir }}/ultimate-backup/{{ item.src }}"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
    remote_src: true
  with_items:
    - { src: "plasmaConfSaver", dest: ".config/" }
    - { src: "konsole", dest: ".local/share/" }

- name: Customization | Restore fonts
  ansible.builtin.copy:
    src: "~/{{ temp_dir }}/ultimate-backup/fonts"
    dest: "/home/{{ custom_user }}/.local/share/"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
    remote_src: true
  notify: Update fonts
