---

# **** Installing KDE Packages | Debian-based
- name: Software | kde | install package
  become_user: root
  apt:
    name: kde-plasma-desktop
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  notify: 
    - Reconfigure display_manager

# **** Installing KDE Packages | Fedora
- name: Software | kde | install package
  become_user: root
  dnf:
    name: "@kde-desktop"
  when: ansible_distribution == "Fedora"

# **** Installing KDE Packages | Arch-based
- name: Software | kde | install package
  become_user: root
  pacman:
    name:
      - plasma 
      - plasma-wayland-session 
      - kde-applications
  when: ansible_distribution == "Archlinux"
  
- name: Software | kde | stop gdm
  service:
    name: gdm
    state: stopped
    enable: false
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde | start sddm
  service:
    name: sddm
    state: started
    enable: true
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde | start NetworkManager
  service:
    name: NetworkManager
    state: started
    enabled: yes
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde | disable kdewallet
  shell: |
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'First Use' 'false'