---
# **** Installing KDE Packages | Debian-based
- name: KDE | Install package
  become_user: root
  ansible.builtin.apt:
    name:
      - kde-plasma-desktop
      - plasma-workspace-wayland
  when: ansible_distribution in ["Debian", "Ubuntu"]

# **** Installing KDE Packages | Fedora
- name: KDE | Install package
  become_user: root
  ansible.builtin.dnf:
    name: "@KDE Plasma Workspaces"
    state: latest
  when: ansible_distribution in ["Fedora", "Rocky"]

# **** Installing KDE Packages | Arch-based
- name: KDE | Install package
  become_user: root
  community.general.pacman:
    name:
      - plasma
      - plasma-wayland-session
      - kde-applications
  when: ansible_distribution == "Archlinux"

- name: KDE services | start sddm
  become_user: root
  ansible.builtin.systemd:
    name: sddm
    enabled: true
    force: true
  when: ansible_distribution in ["Archlinux", "Fedora", "Rocky"]

- name: KDE | SDDM | Change file permissions
  become_user: root
  ansible.builtin.file:
    path: /var/lib/sddm/.config
    owner: sddm
    group: sddm
    mode: "0755"
  when: ansible_distribution == "Archlinux"

- name: KDE services | Start NetworkManager
  become_user: root
  ansible.builtin.systemd:
    name: NetworkManager
    state: started
    enabled: true
  when: ansible_distribution in ["Archlinux", "Fedora", "Rocky"]

- name: KDE services | Disable kwallet
  ansible.builtin.shell: |
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'First Use' 'false'
  args:
    creates: "/home/{{ custom_user }}/.config/kwalletrc"
