---

# **** Installing KDE Packages | Debian-based
- name: Software | kde | install package
  become_user: root
  apt:
    name: kde-plasma-desktop
  when: ansible_distribution in ["Debian", "Ubuntu"]
  notify: 
    - Reconfigure display_manager

# **** Installing KDE Packages | Fedora
- name: Software | kde | install package
  become_user: root
  dnf:
    name: "@KDE Plasma Workspaces"
    state: latest
  when: ansible_distribution == "Fedora"

# **** Installing KDE Packages | Arch-based
- name: Software | kde | install package
  become_user: root
  pacman:
    name:
      - plasma 
      - plasma-wayland-session 
      - kde-applications
  when: ansible_distribution == "Archlinux"

- name: Software | kde services | set graphical.target
  become_user: root
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

#- name: Software | kde services | stat gdm service
#  file: 
#    path: /etc/systemd/system/display-manager.service
#  register: gdm_service_status

- name: System setup | tweaks | Create sddm link
  become_user: root
  file:
    src: /usr/lib/systemd/system/sddm.service
    dest: /etc/systemd/system/display-manager.service
    owner: root
    group: root
    state: link
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde services | start NetworkManager
  service:
    name: NetworkManager
    state: started
    enabled: yes
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde services | disable kwallet
  shell: |
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'First Use' 'false'
  args:
    creates: "/home/{{ custom_user }}/.config/kwalletrc"
  