---

# **** Installing KDE Packages | Debian-based
- name: Software | kde | install package
  become_user: root
  apt:
    name: 
      - kde-plasma-desktop
      - plasma-workspace-wayland
  when: ansible_distribution in ["Debian", "Ubuntu"]

# **** Installing KDE Packages | Fedora
- name: Software | kde | install package
  become_user: root
  dnf:
    name: "@KDE Plasma Workspaces"
    state: latest
  when: ansible_distribution == "Fedora"

# **** Installing KDE Packages | Arch-based
- name: Software | kde | install package
  become_user: root
  pacman:
    name:
      - plasma 
      - plasma-wayland-session 
      - kde-applications
  when: ansible_distribution == "Archlinux"

- name: Software | kde services | switch to sddm
  become_user: root
  command: dpkg-reconfigure -f noninteractive sddm
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | kde services | start NetworkManager
  become_user: root
  systemd:
    name: sddm
    state: started
    enabled: true
    force: true
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde services | start NetworkManager
  become_user: root
  systemd:
    name: NetworkManager
    state: started
    enabled: true
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde services | disable kwallet
  shell: |
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'First Use' 'false'
  args:
    creates: "/home/{{ custom_user }}/.config/kwalletrc"
  