---

# **** Installing KDE Packages | Debian-based
- name: Software | kde | install package
  become_user: root
  apt:
    name: kde-plasma-desktop
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  notify: 
    - Reconfigure display_manager

# **** Installing KDE Packages | Fedora
- name: Software | kde | install package
  become_user: root
  dnf:
    name: "@kde-desktop"
  when: ansible_distribution == "Fedora"

# **** Installing KDE Packages | Arch-based
- name: Software | kde | install package
  become_user: root
  pacman:
    name:
      - plasma 
      - plasma-wayland-session 
      - kde-applications
  when: ansible_distribution == "Archlinux"

- name: Software | kde services | set graphical.target
  become_user: root
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Software | kde services | stat gdm service
  stat: 
    path: /etc/init.d/gdm
  register: gdm_service_status

- name: Software | kde services | stop gdm
  service:
    name: gdm
    state: stopped
    enabled: false
  when: ansible_distribution in ["Archlinux", "Fedora"] and gdm_service_status.stat.exists

- name: Software | kde services | start sddm
  service:
    name: sddm
    state: started
    enabled: true
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde services | start NetworkManager
  service:
    name: NetworkManager
    state: started
    enabled: yes
  when: ansible_distribution in ["Archlinux", "Fedora"]

- name: Software | kde services | stat kdewallet config
  command: "grep -Fxq 'Enabled=true' /home/{{ custom_user }}/.config/kwalletrc"
  failed_when: false
  register: kdewallet_conf

- name: Software | kde services | disable kwallet
  shell: |
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'
    kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'First Use' 'false'
  when: kdewallet_conf.rc == 0