---
# **** Plasma Customization Saver
- name: Plasmoids | Clone plasma saver
  ansible.builtin.git:
    repo: https://github.com/paju1986/PlasmaConfSaver.git
    dest: "~/{{ temp_dir }}/PlasmaConfSaver"
    force: yes

- name: Plasmoids | Install plasma saver
  ansible.builtin.shell: |
    kpackagetool5 -i . || kpackagetool5 -u .
  args:
    chdir: "~/{{ temp_dir }}/PlasmaConfSaver/com.pajuelo.plasmaConfSaver/"
    creates: "/home/{{ custom_user }}/.local/share/plasma/plasmoids/com.pajuelo.plasmaConfSaver"

# **** Latte Spacer
- name: Plasmoids | Clone latte spacer
  ansible.builtin.git:
    repo: https://github.com/psifidotos/applet-latte-spacer.git
    dest: "~/{{ temp_dir }}/applet-latte-spacer"
    force: yes

- name: Plasmoids | Install latte spacer
  ansible.builtin.shell: |
    kpackagetool5 -i . || kpackagetool5 -u .
  args:
    chdir: "~/{{ temp_dir }}/applet-latte-spacer/"
    creates: "/home/{{ custom_user }}/.local/share/plasma/plasmoids/org.kde.latte.spacer"

# **** Better Inline Clock
- name: Plasmoids | Clone better inline clock
  ansible.builtin.git:
    repo: https://github.com/MarianArlt/kde-plasmoid-betterinlineclock.git
    dest: "~/{{ temp_dir }}/kde-plasmoid-betterinlineclock"
    force: yes

- name: Plasmoids | Install better inline clock
  ansible.builtin.shell: |
    kpackagetool5 -i . || kpackagetool5 -u .
  args:
    chdir: "~/{{ temp_dir }}/kde-plasmoid-betterinlineclock/org.kde.plasma.betterinlineclock/"
    creates: "/home/{{ custom_user }}/.local/share/plasma/plasmoids/org.kde.plasma.betterinlineclock"

# **** Inline Battery
- name: Plasmoids | Clone inline battery
  ansible.builtin.git:
    repo: https://github.com/0kzh/mac-inline-battery.git
    dest: "~/{{ temp_dir }}/mac-inline-battery"
    force: yes

- name: Plasmoids | Install inline battery
  ansible.builtin.shell: |
    kpackagetool5 -i . || kpackagetool5 -u .
  args:
    chdir: "~/{{ temp_dir }}/mac-inline-battery/"
    creates: "/home/{{ custom_user }}/.local/share/plasma/plasmoids/org.kde.plasma.inlineBattery"

# **** Thermal Monitor
- name: Plasmoids | Extract thermal monitor
  ansible.builtin.unarchive:
    src: users/custom_user/resources/plasmoids/org.kde.thermalMonitorFix.tar.gz
    dest: "~/{{ temp_dir }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755

- name: Plasmoids | Install thermal monitor
  ansible.builtin.shell: |
    kpackagetool5 -i . || kpackagetool5 -u .
  args:
    chdir: "~/{{ temp_dir }}/org.kde.thermalMonitorFix/"
    creates: "/home/{{ custom_user }}/.local/share/plasma/plasmoids/org.kde.thermalMonitorFix"

# **** Splash Screen
- name: Plasmoids | Clone watch_dogs splash
  ansible.builtin.git:
    repo: https://github.com/ferretwithaberet/watch_dogs-kde-splash.git
    dest: "~/{{ temp_dir }}/watch_dogs-kde-splash"
    force: yes

- name: Plasmoids | Install watch_dogs splash
  ansible.builtin.shell: |
    kpackagetool5 -i . || kpackagetool5 -u .
  args:
    chdir: "~/{{ temp_dir }}/watch_dogs-kde-splash"
    creates: "/home/{{ custom_user }}/.local/share/plasma/look-and-feel/WatchDogsBootSplash"

# **** Systray Latte Tweaks
- name: Plasmoids | Clone latte systray tweaks
  ansible.builtin.git:
    repo: https://github.com/psifidotos/plasma-systray-latte-tweaks.git
    dest: "~/{{ temp_dir }}/plasma-systray-latte-tweaks"
    force: yes

- name: Plasmoids | Copy latte systray tweaks files
  ansible.builtin.copy:
    src: "~/{{ temp_dir }}/plasma-systray-latte-tweaks/{{ item.src }}"
    dest: "/home/{{ custom_user }}/.local/share/plasma/plasmoids/"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { src: "org.kde.plasma.systemtray" }
    - { src: "org.kde.plasma.private.systemtray" }
