---
- name: Ansible setup | Ensure ansible is the latest version
  ansible.builtin.package:
    name: ansible
    state: latest

- name: Ansible setup | Install acl package
  ansible.builtin.package:
    name: acl
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Ansible setup | Create ansible log file
  ansible.builtin.file:
    path: /var/log/ansible.log
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0664
    state: touch
  changed_when: false

- name: Ansible setup | Remove default ansible directory (/etc/ansible) from host
  ansible.builtin.file:
    path: /etc/ansible
    state: absent
