---
- name: System setup | Microcode | Install package Amd
  ansible.builtin.package:
    name: "{{ amd_microcode_package }}"
    state: latest
  when:
    - microcode_amd_install is defined
    - microcode_amd_install == true

- name: System setup | Microcode | Install package Intel
  ansible.builtin.package:
    name: "{{ intel_microcode_package }}"
    state: latest
  when:
    - microcode_intel_install is defined
    - microcode_intel_install == true
