---
- name: System setup | UFW | Install UFW
  ansible.builtin.package:
    name:
      - ufw
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | UFW | UFW allow outgoing
  community.general.ufw:
    default: allow
    direction: outgoing
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | UFW | UFW deny incoming
  community.general.ufw:
    default: deny
    direction: incoming
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | UFW | UFW allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | UFW | Enable UFW
  community.general.ufw:
    state: enabled
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | ufw-docker | Get ufw-docker
  ansible.builtin.shell: |
    wget -O /usr/local/bin/ufw-docker https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
  args:
    creates: "/usr/local/bin/ufw-docker"
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | ufw-docker | Make ufw-docker an executable
  ansible.builtin.file:
    path: /usr/local/bin/ufw-docker
    owner: root
    group: root
    mode: "0755"
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | ufw-docker | Search for ufw-docker rules
  ansible.builtin.lineinfile:
    dest: /etc/ufw/after.rules
    line: "-A DOCKER-USER -j ufw-user-forward"
    state: present
  check_mode: true
  when: ansible_distribution in ["Debian", "Ubuntu"]
  register: ufw_rules_content

- name: System setup | ufw-docker | Install ufw-docker rules
  ansible.builtin.shell: |
    ufw-docker install
  when:
    - ansible_distribution in ["Debian", "Ubuntu"]
    - ufw_rules_content.changed
  register: ufw_rules

- name: System setup | ufw-docker | Restart UFW Service
  ansible.builtin.service:
    name: ufw
    state: restarted
  when:
    - ansible_distribution in ["Debian", "Ubuntu"]
    - ufw_rules.changed
