---
aws_cli: awscli
autojump_package: autojump
amd_microcode_package: amd64-microcode
cron_package: cron
dns_utils_package: dnsutils
intel_microcode_package: intel-microcode
lm_sensors_package: lm-sensors
nfs_client_package: nfs-common
openssh_package: openssh-server
openssh_service: sshd
python_package: python3
python_pip_package: python3-pip
python_psutil_package: python3-psutil
python_virtualenv_package: python3-virtualenv
rename_package: rename
sudo_group: sudo
system_guard: ksystemstats
github_cli: gh
