---

- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  - import_tasks: qemu-agent.yml
    when:
    - proxmox_instance is defined
    - proxmox_instance == true

  - include_tasks: unattended_upgrades.yml
    when:
    - ansible_distribution in ["Debian", "Ubuntu"]
    - unattended_upgrades is defined
    - unattended_upgrades == true

  rescue:
  - set_fact: task_failed=true
