---

- name: Qemu-agent | install package
  package:
    state: latest
    name:
      - qemu-guest-agent
  when: proxmox_instance is defined and proxmox_instance == true
  notify:
    - restart_qemu_agent

- name: Qemu-agent | enable qemu agent daemon
  service:
    name: "{{ qemu_agent_service }}"
    enabled: yes
    state: started
  when: proxmox_instance is defined and proxmox_instance == true
