---

- name: System setup | utilities | install utility packages
  package:
    name:
      - "{{ autojump_package }}"
      - colordiff
      - curl
      - "{{ dns_utils_package }}"
      - "{{ github_cli }}"
      - htop
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - "{{ rename_package }}"
      - rsync
      - sshfs
      - "{{ system_guard }}"
      - tldr
      - traceroute
      - tree
      - wget
      - whois

- name: System setup | utilities | install utility packages (arch)
  pacman:
    name:
      - man-db
      - man-pages
      - github-cli
  when: ansible_distribution == "Archlinux"
  
