---
- name: Software | Development | Install packages
  ansible.builtin.package:
    name:
      - perl
      - "{{ python_flake8_package }}"
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_pyflakes_package }}"
      - pkg-config
      - python-setuptools
      - "{{ python_virtualenv_package }}"
      - ruby
      - "{{ ruby_rake_package }}"
      - tig
    state: latest
  register: dev_pkg

- name: Software | Development | Install packages Arch
  community.general.pacman:
    name:
      - base-devel
  when: ansible_distribution == "Archlinux"

- name: Software | Development | Install packages Debian
  ansible.builtin.apt:
    name:
      - build-essential
      - python-is-python3
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Development | Install packages Fedora
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - "@Development libraries"
    state: latest
  when: ansible_distribution == "Fedora"
