---

- name: Software | Utilities | Install packages
  package:
    name:
      - at
      - git
      - colordiff
      - curl
      - "{{ dns_utils_package }}"
      - "{{ github_cli }}"
      - htop
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - openssl
      - "{{ rename_package }}"
      - rsync
      - sshfs
      - "{{ system_guard }}"
      - tldr
      - traceroute
      - tree
      - wget
      - whois
      - zsh

- name: Software | Utilities | Install autojump
  package:
    name:
      - "{{ autojump_package }}"
  when: ansible_distribution != "Archlinux"

- name: Software | Utilities | Install autojump Arch
  become_user: "{{ custom_user }}"
  kewlfft.aur.aur:
    use: yay
    name: "{{ autojump_package }}"
  when: ansible_distribution == "Archlinux"

- name: Software | Utilities | Install packages Arch
  pacman:
    name:
      - man-db
      - man-pages
      - github-cli
  when: ansible_distribution == "Archlinux"
