- name: System setup | development packages | install packages
  package:
    name:
      - git
      - perl
      - "{{ python_flake8_package }}"
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_pyflakes_package }}"
      - python-setuptools
      - "{{ python_virtualenv_package }}"
      - ruby
      - "{{ ruby_rake_package }}"
      - tig
    state: latest
