---

- name: Software | Docker | Install snap
  snap:
    name: docker

- name: Software | Docker | Create group
  group:
    name: docker
    state: present

- name: Software | Docker | Add user to group
  user:
    name: "{{ custom_user }}"
    groups: docker
    append: yes

- name: Software | Docker Compose | Install package
  package:
    name:
      - docker-compose

# - name: System setup | docker | start docker service
#  service:
#    name: docker
#    state: started
#    enabled: true
#  when: ansible_distribution != "Archlinux"
