---

- name: Software | Utilities | Install packages
  package:
    name:
      - at
      - "{{ aws-cli }}"
      - colordiff
      - curl
      - "{{ cron_package }}"
      - "{{ dns_utils_package }}"
      - "{{ github_cli }}"
      - htop
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - openssl
      - "{{ rename_package }}"
      - rsync
      - sshfs
      - "{{ system_guard }}"
      - terraform
      - tldr
      - traceroute
      - tree
      - wget
      - whois

- name: Software | Utilities | Install autojump
  package:
    name:
      - "{{ autojump_package }}"
  when: ansible_distribution != "Archlinux"

- name: Software | Utilities | Install autojump Arch
  become_user: "{{ custom_user }}"
  kewlfft.aur.aur:
    use: yay
    name: "{{ autojump_package }}"
  when: ansible_distribution == "Archlinux"

- name: Software | Utilities | Install packages Arch
  pacman:
    name:
      - man-db
      - man-pages
      - github-cli
  when: ansible_distribution == "Archlinux"

- name: Software | Utilities | Download SAM
  ansible.builtin.get_url:
    url: https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
    dest: "{{ temp_dir }}/aws-sam-cli-linux-x86_64.zip"
    mode: 0755

- name: Software | Utilities | Unarchive SAM
  unarchive:
    src: "{{ temp_dir }}/aws-sam-cli-linux-x86_64.zip"
    dest: "{{ temp_dir }}/sam-installation"
    mode: 0755

- name: Software | Docker | Install package Debian
  shell: ./install
  args:
    chdir: "{{ temp_dir }}/sam-installation"
    creates: /usr/bin/sam