---

- name: System setup | docker | install snap
  snap:
    name: docker

- name: Users | custom user | create group
  group:
    name: docker
    state: present

- name: System setup | docker | add user to docker group
  user:
    name: "{{ custom_user }}"
    groups: docker
    append: yes

- name: System setup | docker-compose | install docker-compose
  package:
    name:
      - docker-compose

- name: System setup | docker | start docker service
  service:
    name: docker
    state: started
    enabled: true
  