---

- name: System setup | development packages | install packages
  package:
    name:
      - perl
      - "{{ python_flake8_package }}"
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_pyflakes_package }}"
      - python-setuptools
      - "{{ python_virtualenv_package }}"
      - ruby
      - "{{ ruby_rake_package }}"
      - tig
    state: latest

- name: System setup | development packages | install packages
  pacman:
    name: base-devel
    state: latest
  when: ansible_distribution == "Archlinux"

- name: System setup | development packages | install packages
  apt:
    name: build-essential
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: System setup | development packages | install packages
  dnf:
    name:
      - '@Development tools'
      - '@Development libraries'
    state: latest
  when: ansible_distribution == "Fedora"

- name: System setup | development packages | install kubectl
  become_user: root
  snap:
    name: kubectl
    classic: true
