---

- name: System setup | package cleanup | remove unneeded packages
  package:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
  when: ansible_distribution in ["Debian", "Ubuntu"]
  
