---

# **** Installing Snap Package
- name: Software | Tweaks | Install snapd
  become_user: root
  package:
    name: snapd
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu", "Fedora"]

# **** Distro-specific Tasks For Arch
# **** Installing AUR Helper Package
- name: Software | Tweaks | Clone yay Arch
  become_user: "{{ custom_user }}"
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ temp_dir }}/yay"
    update: true
  when: ansible_distribution == "Archlinux"

- name: Software | Tweaks | Install yay Arch
  become_user: "{{ custom_user }}"
  command:
    chdir: "{{ temp_dir }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
  when: ansible_distribution == "Archlinux"

# **** Installing Snap Package | Arch-based
- name: Software | Tweaks | Install snap Arch
  become_user: "{{ custom_user }}"
  kewlfft.aur.aur:
    use: yay
    name: snapd
  when: ansible_distribution == "Archlinux"

- name: Software | Tweaks | Enable snapd
  service:
    name: snapd
    state: started
    enabled: true

- name: Software | Tweaks | Create snap soft link
  become_user: root
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link
  when: ansible_distribution != "Ubuntu"

- name: Software | Tweaks | Enable snapd.apparmor Arch
  service:
    name: snapd.apparmor
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

# **** Installing Snap Core Package
- name: Software | Tweaks | Install/update core snap
  snap:
    name: core

# **** Distro-specific Tasks For Ubuntu
- name: Software | Tweaks | Disable apport Ubuntu
  lineinfile:
    dest: /etc/default/apport
    regexp: "enabled="
    line: "enabled=0"
  failed_when: false
  when: ansible_distribution in ["Ubuntu"]

- name: Software | Tweaks | Stop apport Ubuntu
  service:
    name: apport
    state: stopped
    enabled: no
  failed_when: false
  when: ansible_distribution in ["Ubuntu"]
