---

- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    # User Configuration
    - import_tasks: user_setup/root_config.yml
    - import_tasks: user_setup/user_config.yml

    # Set up the ansible environment
    - import_tasks: system_setup/ansible_setup.yml

    # Install software
    - import_tasks: software/repositories.yml
    - import_tasks: software/packages_development.yml
    - import_tasks: software/tweaks.yml
    - import_tasks: software/packages_docker.yml
    - import_tasks: software/packages_cleanup.yml
    - import_tasks: software/packages_utilities.yml

    # Perform remaining tasks:
    - import_tasks: system_setup/logging.yml
    - import_tasks: system_setup/microcode.yml
    - import_tasks: system_setup/openssh.yml
    - import_tasks: system_setup/ufw.yml

  rescue:
    - set_fact: task_failed=true
