---
- name: Users | Custom | Stat .config folder
  ansible.builtin.stat:
    path: "/home/{{ custom_user }}/.config"
  register: config_dir

- name: Users | Custom | Create config directories
  ansible.builtin.file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0700
  with_items:
    - { dir: ".config" }
  when: config_dir.stat.exists == false

- name: Users | Custom | Create personal config directories
  ansible.builtin.file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: .local/share/kservices5 }
    - { dir: .local/share/kwin/scripts }
    - { dir: .local/share/kwin/scripts/forceblur }
    - { dir: .icons }

- name: Users | Custom | Clone backups
  become_user: "{{ custom_user }}"
  ansible.builtin.git:
    repo: https://github.com/jokerwrld999/ultimate-backup.git
    dest: "~/{{ temp_dir }}/ultimate-backup"
    force: yes

- name: Users | Custom | Restore backup
  ansible.builtin.copy:
    src: "~/{{ temp_dir }}/ultimate-backup/{{ item.src }}"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { src: "fonts", dest: ".local/share/" }
    - { src: "walls", dest: "/.local/share/wallpapers/" }

- name: Users | Custom | Restore backup
  ansible.builtin.copy:
    src: "users/custom_user/{{ item.src }}"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { src: "bpytop.conf", dest: ".config/bpytop/bpytop.conf" }
    - { src: "resources/splash_screen/ksplashrc", dest: ".config" }
