---

- name: Release upgrade | Remove the EOL message of the day if one exists.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d/99-esm
    - /run/motd.dynamic

- name: Release upgrade | Upgrade all packages to the latest version
  apt: 
    update_cache: true
    cache_valid_time: 3600
    upgrade: full
  
- name: Release upgrade | Reboot the server.
  reboot:

- name: Release upgrade | Ensure update-manager-core is installed.
  apt: name=update-manager-core state=present

- name: Release upgrade | Run do-release-upgrade non-interactively.
  command: do-release-upgrade -f DistUpgradeViewNonInteractive

- name: Release upgrade | Reboot the server.
  reboot:
