---

- name: Release upgrade | Upgrade all packages to the latest version
  apt: 
    update_cache: true
    cache_valid_time: 3600
    upgrade: 'yes'
  register: upgrade

- name: Release upgrade | Reboot the server.
  reboot:
  when: upgrade.changed

- name: Release upgrade | Ensure update-manager-core is installed.
  apt: 
    name: 
      update-manager-core 
    state: present

- name: Release upgrade | Run do-release-upgrade non-interactively.
  command: do-release-upgrade -f DistUpgradeViewNonInteractive
  failed_when: false
  register: release_upgrade

- name: Release upgrade | Reboot the server.
  reboot:
  when: release_upgrade.stdout is not search('no development version')
