---

- name: Send completion notification via telegram
  tags: always
  telegram:
    token: "{{ telegram_token }}"
    api_args:
      chat_id: "{{ telegram_chat_id }}"
      parse_mode: markdown
      text: "✔️  Ansible provision finished on *{{ ansible_hostname }}*"
  changed_when: False
