---
- name: Unattended upgrades | Install unattended-upgrades for debian-based hosts
  ansible.builtin.package:
    state: latest
    name:
      - unattended-upgrades
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Unattended upgrades | Copy 20auto-upgrades file for debian-based hosts
  ansible.builtin.copy:
    src: unattended-upgrades/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Unattended upgrades | Copy 50unattended-upgrades file (debian)
  ansible.builtin.copy:
    src: unattended-upgrades/50unattended-upgrades_debian
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Debian"

- name: Unattended upgrades | Copy 50unattended-upgrades file (ubuntu)
  ansible.builtin.copy:
    src: unattended-upgrades/50unattended-upgrades_ubuntu
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu"
