---

- name: Ansible setup | Ensure ansible is the latest version
  package:
    name: ansible
    state: latest

- name: Ansible setup | Install required packages
  package:
    name:
      - "{{ dconf_package }}"
      - "{{ python_psutil_package }}"

- name: Ansible setup | Install acl package
  package:
    name: acl
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Ansible setup | Create ansible log file
  file:
    path: /var/log/ansible.log
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0664
    state: touch
  changed_when: false

- name: Ansible setup | Remove default ansible directory (/etc/ansible) from host
  file:
    path: /etc/ansible
    state: absent
