---

- name: System setup | OpenSSH | Install package
  package:
    name: "{{ openssh_package }}"
    state: latest
  notify: restart_sshd

- name: System setup | OpenSSH | Enable daemon
  service:
    name: "{{ openssh_service }}"
    enabled: yes
    state: started

- name: System setup | OpenSSH | Generate sshd_config file from template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: System setup | OpenSSH | Copy issue.net
  copy:
    src: system_setup/openssh_issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
